name: Build for Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - '**.MD'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libxcb-xinerama0 libfontconfig1 libdbus-1-3
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller --no-binary pyinstaller
          
      - name: Build Linux executable
        run: |
          python setup.py build_binary
          chmod +x dist/eReader_CBZ_Manga_Converter_linux_*
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/eReader_CBZ_Manga_Converter_linux_*
          
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/eReader_CBZ_Manga_Converter_linux_* 