name: Build for macOS

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - '**.MD'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-14]  # Support Intel and Apple Silicon
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller certifi
          pip install -r requirements.txt
          
      - name: Install Node.js for appdmg
        uses: actions/setup-node@v4
        with:
          node-version: 16
          
      - name: Install appdmg
        run: npm install -g appdmg
          
      - name: Build macOS binary
        run: |
          python setup.py build_binary
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ runner.arch }}
          path: |
            dist/*.dmg
            dist/*.app
            
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            CHANGELOG.md
            LICENSE
            dist/*.dmg 