name: Build for macOS

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - '**.MD'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-14]  # 支持Intel和Apple Silicon
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt
          
      - name: Build macOS app
        run: |
          python setup.py build_binary
          
      - name: Create DMG (optional)
        run: |
          # 如果有 app.icns 和足够的配置，可以创建DMG
          # 这里简化处理，直接压缩.app文件
          cd dist
          APP_NAME="eReader CBZ Manga Converter.app"
          if [ -d "$APP_NAME" ]; then
            tar -czf "eReader_CBZ_Manga_Converter_macOS_${{ runner.arch }}.tar.gz" "$APP_NAME"
          fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ runner.arch }}
          path: |
            dist/*.tar.gz
            dist/*.app
            
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.tar.gz 