name: Build and Release

"on":
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - '**.MD'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: write    # Required for creating releases and uploading assets
  actions: read      # Required for downloading artifacts

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact-name: linux-build
            build-command: "python build.py build-linux"
            setup-deps: |
              sudo apt-get update -qq
              sudo apt-get install -y -qq libgl1 libxcb-xinerama0 libfontconfig1 libdbus-1-3 libegl1-mesa libxkbcommon-x11-0 libxkbcommon0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 || echo "Some packages may not be available"
              echo "Installing 7z for KCC support..."
              sudo apt-get install -y -qq p7zip-full || echo "7z installation failed"
              echo "Verifying 7z installation..."
              7z || echo "7z installation verification failed"
          - os: windows-latest
            platform: windows
            artifact-name: windows-build
            build-command: "python build.py build-win"
            setup-deps: |
              echo "Installing 7z for KCC support..."
              choco install 7zip -y
              echo "Verifying 7z installation..."
              7z || echo "7z installation verification failed"
          - os: macos-13
            platform: macos-intel
            artifact-name: macos-intel-build
            build-command: "python build.py build-mac"
            setup-deps: |
              echo "Installing appdmg for DMG creation..."
              npm install -g appdmg
              echo "Verifying appdmg installation..."
              appdmg --version || echo "appdmg installation verification failed"
              echo "Installing 7z for KCC support..."
              brew install p7zip
              echo "Verifying 7z installation..."
              7z || echo "7z installation verification failed"
          - os: macos-latest
            platform: macos-arm
            artifact-name: macos-arm-build
            build-command: "python build.py build-mac"
            setup-deps: |
              echo "Installing appdmg for DMG creation..."
              npm install -g appdmg
              echo "Verifying appdmg installation..."
              appdmg --version || echo "appdmg installation verification failed"
              echo "Installing 7z for KCC support..."
              brew install p7zip
              echo "Verifying 7z installation..."
              7z || echo "7z installation verification failed"
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install Node.js (for macOS DMG creation)
        if: startsWith(matrix.platform, 'macos')
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install system dependencies
        if: matrix.setup-deps != ''
        run: ${{ matrix.setup-deps }}

      - name: Verify appdmg installation (macOS only)
        if: startsWith(matrix.platform, 'macos')
        run: |
          echo "Checking appdmg installation..."
          which appdmg || (echo "ERROR: appdmg not found in PATH" && exit 1)
          appdmg --version || (echo "ERROR: appdmg not working" && exit 1)
          echo "✅ appdmg is ready"

      - name: Setup KCC environment
        run: |
          python build.py kcc
        shell: bash
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyinstaller certifi
          
      - name: Install project dependencies
        run: |
          pip install -e ".[build]"
        shell: bash
          
      - name: Build binary
        run: ${{ matrix.build-command }}
        shell: bash
          
      - name: Prepare artifacts (Linux)
        if: matrix.platform == 'linux'
        run: |
          find dist/ -type f -executable -exec chmod +x {} \; || true
          ls -la dist/
          
      - name: Prepare artifacts (Windows)
        if: matrix.platform == 'windows'
        run: |
          dir dist\
          
      - name: Prepare artifacts (macOS)
        if: startsWith(matrix.platform, 'macos')
        run: |
          ls -la dist/
          echo "Checking .app bundle size:"
          du -sh dist/*.app || echo "No .app found"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.exe
            dist/*_1.*.*.exe
            dist/*_1.*.*.dmg
            dist/*_1.*.*.zip
          if-no-files-found: warn
          retention-days: 7
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # Required for creating releases
      actions: read    # Required for downloading artifacts
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          
      - name: Display structure of downloaded files
        run: |
          ls -la release-artifacts/
          find release-artifacts/ -type f
          
      - name: Prepare release files
        run: |
          mkdir -p release-files
          
          # Copy Linux binaries
          if [ -d "release-artifacts/linux-build" ]; then
            cp -r release-artifacts/linux-build/* release-files/ 2>/dev/null || true
          fi
          
          # Copy Windows binaries
          if [ -d "release-artifacts/windows-build" ]; then
            cp -r release-artifacts/windows-build/* release-files/ 2>/dev/null || true
          fi
          
          # Copy macOS Intel binaries
          if [ -d "release-artifacts/macos-intel-build" ]; then
            cp -r release-artifacts/macos-intel-build/* release-files/ 2>/dev/null || true
          fi
          
          # Copy macOS ARM binaries
          if [ -d "release-artifacts/macos-arm-build" ]; then
            cp -r release-artifacts/macos-arm-build/* release-files/ 2>/dev/null || true
          fi
          
          # List final release files
          echo "Final release files:"
          ls -la release-files/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            CHANGELOG.md
            release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 